version: '3'
services:
    jenkins:
        image: jenkins/jenkins:lts-jdk17
        privileged: true
        user: root        
        ports:
            - 8080:8080
            - 50000:50000
        container_name: jenkins
        volumes:
            - $PWD/jenkins_compose:/var/jenkins_home
            - /var/run/docker.sock:/var/run/docker.sock            
        networks:
            - devops_net
    sonarqube:
        image: sonarqube:latest
        ports:
            - 9000:9000
        container_name: sonarqube
          #volumes:
          #  - sonarqube_data:/opt/sonarqube/data
        environment:
            SONARQUBE_USERNAME: admin
            SONARQUBE_PASSWORD: pIn#h1E8
        networks:
            - devops_net
networks:
    devops_net: